const
  INPUT_USERNAME = 'INPUT_USERNAME',
  INPUT_PASSWORD = 'INPUT_PASSWORD',
  PENDING_CREDENTIALS = 'PENDING_CREDENTIALS',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  LOGGED_IN_CREDENTIALS = 'LOGGED_IN_CREDENTIALS';

module.exports = {
  INPUT_USERNAME,
  INPUT_PASSWORD,
  PENDING_CREDENTIALS,
  INVALID_CREDENTIALS,
  LOGGED_IN_CREDENTIALS
};